name: Build EXE on exe commit

on:
  push:
    branches:
      - main
    # Only run if commit message contains 'exe'
    # This uses a filter in the workflow itself (see 'if' in jobs)

jobs:
  build-exe:
    runs-on: windows-latest
    if: contains(github.event.head_commit.message, 'exe')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ==================================
      #        64-bit (x64) Build
      # ==================================
      - name: Set up 64-bit Python 3.10
        uses: actions/setup-python@v5 # Use the latest version
        with:
          python-version: '3.10'
          architecture: 'x64'

      - name: Install dependencies (x64)
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller jdatetime openpyxl requests

      - name: Build 64-bit EXE
        run: pyinstaller --onefile --name main_x64 main.py

      - name: Upload 64-bit EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: main_x64
          path: dist/main_x64.exe

      # ==================================
      #        32-bit (x86) Build
      # ==================================
      - name: Set up 32-bit Python 3.10
        uses: actions/setup-python@v5 # Use the action again for the 32-bit version
        with:
          python-version: '3.10'
          architecture: 'x86' # Specify x86 architecture here

      - name: Install dependencies (x86)
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller jdatetime openpyxl requests

      - name: Build 32-bit EXE
        run: pyinstaller --onefile --name main_x86 main.py

      - name: Upload 32-bit EXE artifact
        uses: actions/upload-artifact@v4
        with:
          name: main_x86
          path: dist/main_x86.exe